services:
    cache:
        container_name: onerpm-cache
        image: redis:alpine

    database:
        container_name: onerpm-db
        image: mariadb:11.0
        network_mode: host
        restart: 'no'
        tty: true
        expose:
            - 3306
        environment:
            MARIADB_ROOT_PASSWORD: onerpm
            MARIADB_DATABASE: onerpm
            MARIADB_USER: onerpm
            MARIADB_PASSWORD: onerpm
        volumes:
            - ./application/vendor/mariadb:/var/lib/mariadb

    webserver:
        container_name: onerpm-srv
        image: php:8.4.3-apache
        network_mode: host
        build:
            context: ./
            dockerfile: php.Dockerfile
        expose:
            - 80
            - 443
        volumes:
            - ./application:/var/www
            - ./application/public:/var/www/html

volumes:
    mariadb:
    www:
    html: