name: Run tests

on: [push]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none

      - name: Prepare Laravel Application
        run: |
          cd application
          cp .env.ci .env

      - name: Install and build
        run: |
          cd application
          composer install -n --prefer-dist
          npm install
          npm run build

      - name: Run tests
        run: |
          cd application
          php artisan migrate
          php artisan test